# Generated by Django 5.2.1 on 2025-06-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointment_cancellation_reason_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
