# Generated by Django 5.2.2 on 2025-06-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_review_doctor_alter_client_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другое')], default='O', max_length=1, verbose_name='Пол'),
        ),
    ]
