# Generated by Django 4.2.21 on 2025-09-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Видео файл (MP4)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (для YouTube/Vimeo)'),
        ),
    ]
